### ISSUE TITLE
rbot crashing in timers.js:358:17

### ISSUE THREAD

**Issue by nixnax** [rom1504/rbot#31]
Windows 7/64, Node v0.12.4, npm 2.11.3, Python 2.7, openssl 1.0.2.c

**Problem: rbot crashes on commands such as smove r1,0,0**

With: typeError: undefined is not a function

See crash dump below:

c:\Users\gap\rbot>node rbot.js localhost 25565 my_id my_password 

I have 20 health and 20 food

Received New Command: smove r2,0,0

["smove",[["position","r2,0,0"]]]

["repeatUntil",[["exp",["ssumove",[["position","-144,79,-69"]]]],["condition",["at",[["position","-144,79,-69"]]]]]]
I'm going to achieve task ["repeatUntil",[["exp",["ssumove",[["position","-144,79,-69"]]]],["condition",["at",[["position","-144,79,-69"]]]]]]
{ x: -146, y: 79, z: -69 }
{ status: 'success', 
  path:
   [ { x: -145.5, y: 79, z: -68.5 },
     { x: -144.5, y: 79, z: -68.5 },
     { x: -143.5, y: 79, z: -68.5 } ] }
["taskList",[["taskList",[["exp",["sumove",[["position","-145.5,79,-68.5"]]]],["exp",["sumove",[["position","-144.5,79,-68.5"]]]],["exp",["sumove",[["position","-143.5,79,-68.5"]]]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["sumove",[["position","-145.5,79,-68.5"]]]],["exp",["sumove",[["position","-144.5,79,-68.5"]]]],["exp",["sumove",[["position","-143.5,79,-68.5"]]]]]]]]

["nothing",[]]
I'm going to achieve task ["nothing",[]]
I achieved task ["nothing",[]]

["dig forward",[["position","r1,0,0"]]]

["taskList",[["taskList",[["exp",["sdig",[["position","r1,0,0"]]]],["exp",["sdig",[["position","-145,80,-69"]]]],["exp",["sbuild",[["position","-145,78,-69"]]]],["exp",["move to",[["position","r1,0,0"]]]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["sdig",[["position","r1,0,0"]]]],["exp",["sdig",[["position","-145,80,-69"]]]],["exp",["sbuild",[["position","-145,78,-69"]]]],["exp",["move to",[["position","r1,0,0"]]]]]]]]

["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","r1,0,0"]]]]]]]]],["condition",["is empty",[["position","r1,0,0"]]]]]]
I'm going to achieve task ["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","r1,0,0"]]]]]]]]],["condition",["is empty",[["position","r1,0,0"]]]]]]
I achieved task ["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","r1,0,0"]]]]]]]]],["condition",["is empty",[["position","r1,0,0"]]]]]]

["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","-145,80,-69"]]]]]]]]],["condition",["is empty",[["position","-145,80,-69"]]]]]]
I'm going to achieve task ["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","-145,80,-69"]]]]]]]]],["condition",["is empty",[["position","-145,80,-69"]]]]]]
I achieved task ["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","-145,80,-69"]]]]]]]]],["condition",["is empty",[["position","-145,80,-69"]]]]]]

["ifThen",[["condition",["is empty",[["position","-145,78,-69"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","item to build"]]]],["exp",["build",[["position","-145,78,-69"]]]]]]]]]]]
I'm going to achieve task ["ifThen",[["condition",["is empty",[["position","-145,78,-69"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","itemto build"]]]],["exp",["build",[["position","-145,78,-69"]]]]]]]]]]]
I achieved task ["ifThen",[["condition",["is empty",[["position","-145,78,-69"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","item to build"]]]],["exp",["build",[["position","-145,78,-69"]]]]]]]]]]]

I'm going to achieve task ["move to",[["position","r1,0,0"]]]
success 2
I achieved task ["move to",[["position","r1,0,0"]]]

I achieved task ["taskList",[["taskList",[["exp",["sdig",[["position","r1,0,0"]]]],["exp",["sdig",[["position","-145,80,-69"]]]],["exp",["sbuild",[["position","-145,78,-69"]]]],["exp",["move to",[["position","r1,0,0"]]]]]]]]

timers.js:358
      immediate._onImmediate();
                ^
TypeError: undefined is not a function
    at processImmediate [as _immediateCallback] (timers.js:358:17)

c:\Users\gap\rbot>

**Comment by rom1504** [comment]
It sounds like a node version issue.

**Comment by nixnax** [comment]
Node version issue?  Any idea how to check?

**Comment by nixnax** [comment]
Found part of the error:
in rbot.js, line "mineflyer.createbot" you forgot to add: 

password:process.argv[5]

The real error is most likely an unreported login error somewhere down in createbot.

**Comment by nixnax** [comment]
##Another log of a timers.js crash, this time in node v0.12.6

dig forward r0,0,1

["dig forward",[["position","r0,0,1"]]]
["taskList",[["taskList",[["exp",["sdig",[["position","r0,0,1"]]]],["exp",["sdig",[["position","-211,73,264"]]]],["exp",["sbuild",[["position","-211,71,264"]]]],["exp",["move to",["position","r0,0,1"]]]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["sdig",[["position","r0,0,1"]]]],["exp",["sdig",[["position","-211,73,264"]]]],["exp",["sbuild",[["position","-211,71,264"]]]],["exp",["move to",[["position","r0,0,1"]]]]]]]]
["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","r0,0,1"]]]]]]]]],["condition",["is empty",[["position","r0,0,1"]]]]]]
I'm going to achieve task ["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","r0,0,1"]]]]]]]]],["condition",["is empty",[["position","r0,0,1"]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["ssdig",[["position","r0,0,1"]]]]]]]]
["ifThen",[["condition",["is not empty",[["position","r0,0,1"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","tool to break grass"]]]],["exp",["dig",[["position","r0,0,1"]]]]]]]]]]]
I'm going to achieve task ["ifThen",[["condition",["is not empty",[["position","r0,0,1"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","tool to break grass"]]]],["exp",["dig",[["position","r0,0,1"]]]]]]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","tool to break grass"]]]],["exp",["dig",[["position","r0,0,1"]]]]]]]]
I'm going to achieve task ["equip",[["destination","hand"],["item","tool to break grass"]]]
I'm going to achieve task ["dig",[["position","r0,0,1"]]]
I dig position (-211, 72, 264)

timers.js:367
      immediate._onImmediate();
                ^
TypeError: undefined is not a function
    at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by nixnax** [comment]
Opened more clear description
