### ISSUE TITLE
mineflayer.createBot() fails silently in Windows

### ISSUE THREAD

**Issue by nixnax** [rom1504/rbot#33]
I had to add   "password:process.argv[5]"  to bot=mineflayer.createBot({}) to log in to 1.8.3 server.

The bot.chat("/login "+process.argv[5]) seems to fail - instead of logging in, node drops back to the command line with no error message at all.

Adding the password parameter back to createBot allows me to log in.

process:
versions:
   { http_parser: '2.3',
     node: '0.12.6',
     v8: '3.28.71.19',
     uv: '1.6.1',
     zlib: '1.2.8',
     modules: '14',
     openssl: '1.0.1o' },
  arch: 'x64',
  platform: 'win32',  (Windows 7)

**Comment by rom1504** [comment]
oh I fixed that in 6e5deaf42513e53bf99ae42f7432ea0fb05b3c8a some time ago but didn't make a new version yet, I will !

**Comment by nixnax** [comment]
Thanks Romain! This is awesome stuff!
