### ISSUE TITLE
full source?

### ISSUE THREAD

**Issue by TheTechPony** [rom1504/rbot#44]
Could you post a translated source by any chance? I'm still learning how to make the bot do things and would like to learn from this.

**Comment by rom1504** [comment]
The full source is in the repo.
Translated ? Translated to what ?

**Comment by TheTechPony** [comment]
It looks like you have made your own coding language in the grammar section, am I wrong?

**Comment by rom1504** [comment]
Yes. It's directly interpreted though, it's not compiled to anything.

**Comment by TheTechPony** [comment]
Was that function in the main grammar file for translating it back or is there any way I can see it without having to manually read it?

**Comment by rom1504** [comment]
There is no translation happening. It is interpreted, that means it's read then functions are executed depending on it.
It's similar to how a server or a bot executes commands.

Yes you have to read the .js file and probably the grammar definition. Obviously don't read the generated parser though.
