### ISSUE TITLE
repeat spiral down done <--- Error

### ISSUE THREAD

**Issue by bshuler** [rom1504/rbot#46]
game { levelType: 'default',
  gameMode: 'survival',
  hardcore: false,
  dimension: 'overworld',
  difficulty: 'easy',
  maxPlayers: 20 }
repeat spiral down done
["repeat",[["exp",["taskList",[["taskList",[["exp",["smove",[["position","r1,-1,0"]]]],["exp",["smove",[["position","r0,-1,1"]]]],["exp",["smove",[["position","r-1,-1,0"]]]],["exp",["smove",[["position","r0,-1,-1"]]]]]]]]]]]
I'm going to achieve task ["repeat",[["exp",["taskList",[["taskList",[["exp",["smove",[["position","r1,-1,0"]]]],["exp",["smove",[["position","r0,-1,1"]]]],["exp",["smove",[["position","r-1,-1,0"]]]],["exp",["smove",[["position","r0,-1,-1"]]]]]]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["smove",[["position","r1,-1,0"]]]],["exp",["smove",[["position","r0,-1,1"]]]],["exp",["smove",[["position","r-1,-1,0"]]]],["exp",["smove",[["position","r0,-1,-1"]]]]]]]]
["repeatUntil",[["exp",["ssumove",[["position","444,64,1783"]]]],["condition",["at",[["position","444,64,1783"]]]]]]
I'm going to achieve task ["repeatUntil",[["exp",["ssumove",[["position","444,64,1783"]]]],["condition",["at",[["position","444,64,1783"]]]]]]
Vec3 { x: 443, y: 65, z: 1783 }
{ status: 'success',
  path:
   [ Vec3 { x: 443.5, y: 65, z: 1783.5 },
     Vec3 { x: 444.5, y: 65, z: 1783.5 },
     Vec3 { x: 444.5, y: 64, z: 1783.5 } ] }
["taskList",[["taskList",[["exp",["sumove",[["position","443.5,65,1783.5"]]]],["exp",["sumove",[["position","444.5,65,1783.5"]]]],["exp",["sumove",[["position","444.5,64,1783.5"]]]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["sumove",[["position","443.5,65,1783.5"]]]],["exp",["sumove",[["position","444.5,65,1783.5"]]]],["exp",["sumove",[["position","444.5,64,1783.5"]]]]]]]]
["nothing",[]]
I'm going to achieve task ["nothing",[]]
I achieved task ["nothing",[]]
["dig forward",[["position","r1,0,0"]]]
["taskList",[["taskList",[["exp",["sdig",[["position","r1,0,0"]]]],["exp",["sdig",[["position","444,66,1783"]]]],["exp",["sbuild",[["position","444,64,1783"]]]],["exp",["move to",[["position","r1,0,0"]]]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["sdig",[["position","r1,0,0"]]]],["exp",["sdig",[["position","444,66,1783"]]]],["exp",["sbuild",[["position","444,64,1783"]]]],["exp",["move to",[["position","r1,0,0"]]]]]]]]
["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","r1,0,0"]]]]]]]]],["condition",["is empty",[["position","r1,0,0"]]]]]]
I'm going to achieve task ["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","r1,0,0"]]]]]]]]],["condition",["is empty",[["position","r1,0,0"]]]]]]
I achieved task ["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","r1,0,0"]]]]]]]]],["condition",["is empty",[["position","r1,0,0"]]]]]]
["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","444,66,1783"]]]]]]]]],["condition",["is empty",[["position","444,66,1783"]]]]]]
I'm going to achieve task ["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","444,66,1783"]]]]]]]]],["condition",["is empty",[["position","444,66,1783"]]]]]]
I achieved task ["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","444,66,1783"]]]]]]]]],["condition",["is empty",[["position","444,66,1783"]]]]]]
["ifThen",[["condition",["is empty",[["position","444,64,1783"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","item to build"]]]],["exp",["build",[["position","444,64,1783"]]]]]]]]]]]
I'm going to achieve task ["ifThen",[["condition",["is empty",[["position","444,64,1783"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","item to build"]]]],["exp",["build",[["position","444,64,1783"]]]]]]]]]]]
I achieved task ["ifThen",[["condition",["is empty",[["position","444,64,1783"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","item to build"]]]],["exp",["build",[["position","444,64,1783"]]]]]]]]]]]
I'm going to achieve task ["move to",[["position","r1,0,0"]]]
success 2
I achieved task ["move to",[["position","r1,0,0"]]]
I achieved task ["taskList",[["taskList",[["exp",["sdig",[["position","r1,0,0"]]]],["exp",["sdig",[["position","444,66,1783"]]]],["exp",["sbuild",[["position","444,64,1783"]]]],["exp",["move to",[["position","r1,0,0"]]]]]]]]
["taskList",[["taskList",[["exp",["tcc",[]]],["exp",["sbuild",[["position","r0,-2,0"]]]],["exp",["sdig",[["position","r0,-1,0"]]]],["exp",["wait",[["int","400"]]]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["tcc",[]]],["exp",["sbuild",[["position","r0,-2,0"]]]],["exp",["sdig",[["position","r0,-1,0"]]]],["exp",["wait",[["int","400"]]]]]]]]
I'm going to achieve task ["tcc",[]]
I achieved task ["tcc",[]]
["ifThen",[["condition",["is empty",[["position","r0,-2,0"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","item to build"]]]],["exp",["build",[["position","r0,-2,0"]]]]]]]]]]]
I'm going to achieve task ["ifThen",[["condition",["is empty",[["position","r0,-2,0"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","item to build"]]]],["exp",["build",[["position","r0,-2,0"]]]]]]]]]]]
I achieved task ["ifThen",[["condition",["is empty",[["position","r0,-2,0"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","item to build"]]]],["exp",["build",[["position","r0,-2,0"]]]]]]]]]]]
["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","r0,-1,0"]]]]]]]]],["condition",["is empty",[["position","r0,-1,0"]]]]]]
I'm going to achieve task ["repeatUntil",[["exp",["taskList",[["taskList",[["exp",["ssdig",[["position","r0,-1,0"]]]]]]]]],["condition",["is empty",[["position","r0,-1,0"]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["ssdig",[["position","r0,-1,0"]]]]]]]]
["ifThen",[["condition",["is not empty",[["position","r0,-1,0"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","tool to break stone"]]]],["exp",["dig",[["position","r0,-1,0"]]]]]]]]]]]
I'm going to achieve task ["ifThen",[["condition",["is not empty",[["position","r0,-1,0"]]]],["exp",["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","tool to break stone"]]]],["exp",["dig",[["position","r0,-1,0"]]]]]]]]]]]
I'm going to achieve task ["taskList",[["taskList",[["exp",["equip",[["destination","hand"],["item","tool to break stone"]]]],["exp",["dig",[["position","r0,-1,0"]]]]]]]]
I'm going to achieve task ["equip",[["destination","hand"],["item","tool to break stone"]]]
/Users/bshuler/Downloads/rbot/lib/inventory.js:18
    var okTools = block.harvestTools;
                       ^

TypeError: Cannot read property 'harvestTools' of undefined
    at canHarvest (/Users/bshuler/Downloads/rbot/lib/inventory.js:18:24)
    at Object.toolToBreak (/Users/bshuler/Downloads/rbot/lib/inventory.js:31:7)
    at stringToItem (/Users/bshuler/Downloads/rbot/lib/stringTo.js:146:76)
    at item (/Users/bshuler/Downloads/rbot/lib/stringTo.js:21:38)
    at /Users/bshuler/Downloads/rbot/lib/stringTo.js:39:119
    at /Users/bshuler/Downloads/rbot/node_modules/async/lib/async.js:356:13
    at async.forEachOf.async.eachOf (/Users/bshuler/Downloads/rbot/node_modules/async/lib/async.js:233:13)
    at _asyncMap (/Users/bshuler/Downloads/rbot/node_modules/async/lib/async.js:355:9)
    at Object.map (/Users/bshuler/Downloads/rbot/node_modules/async/lib/async.js:337:20)
    at Object.stringTo (/Users/bshuler/Downloads/rbot/lib/stringTo.js:39:8)

**Comment by rom1504** [comment]
that error is now fixed
