### ISSUE TITLE
Cannot run the script

### ISSUE THREAD

**Issue by Ganondorf629** [rom1504/rbot#47]
I wrote this cmd: 
```
rbot mc.howlcraft.fr 25565 emailofmybot secretpasswordofmybot myusername
PAUSE
```

but when I run the script, I get this error:
http://i.imgur.com/NGuZoN4.png

**Comment by Ezcha** [comment]
Run it as "node rbot mc.howlcraft.fr 25565 emailofmybot secretpasswordofmybot myusername"

**Comment by Ganondorf629** [comment]
Thank you ! :)

**Comment by Ganondorf629** [comment]
I need help https://github.com/rom1504/rbot/issues/48
