### ISSUE TITLE
Cannot find module './grammar/grammar' and BOT doesn't do anything when connected to server

### ISSUE THREAD

**Issue by Ganondorf629** [rom1504/rbot#48]
Hi, when I launch the script I get this error:

<< Cannot find module './grammar/grammar' >>

I did /npm install grammar though and it has been successfully installed

EDIT:
I replaced the missing grammar.js file by index.js file from grammar module, and it worked !

However, my bot doesn't do anything when I ask him to. eg when I tell him 'pos Ganondorf629' he won't answer anything...

**Comment by Ganondorf629** [comment]
I replaced the missing grammar.js file by index.js file from grammar module, and it worked !

However, my bot doesn't do anything when I ask him to. eg when I tell him 'pos Ganondorf629' he won't answer anything...

**Comment by rom1504** [comment]
just run `npm install`

**Comment by Ganondorf629** [comment]
I know but the bot doesn't do anything

**Comment by rom1504** [comment]
undo "I replaced the missing grammar.js file by index.js file from grammar module, and it worked !"
then run `npm install` in the rbot dir.
Then try again

**Comment by Ganondorf629** [comment]
It still doesn't work :/

**Comment by Ryah** [comment]
I'm getting the same error. I cloned the github repo and ran `npm install -g`,  here is the error log for me.

```
module.js:471
    throw err;
    ^

Error: Cannot find module './grammar/grammar'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/rbot/achieve.js:2:42)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
