### ISSUE TITLE
Unhandled error?

### ISSUE THREAD

**Issue by ali6836** [rom1504/rbot#51]
So I'm trying to login to pvp.desteria.com, and I keep getting an unhandled error. This is what I get
I logged in.
settings { chat: 'enabled',
  colorsEnabled: true,
  viewDistance: 'far',
  difficulty: 2,
  showCape: true }
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: unexpected end of file
    at Zlib._handle.onerror (zlib.js:370:17)

**Comment by rom1504** [comment]
https://github.com/PrismarineJS/node-minecraft-protocol/issues/462

**Comment by rom1504** [comment]
fixed
