### ISSUE TITLE
Sometimes bot only shows Welcomes and Leaves in the Terminal

### ISSUE THREAD

**Issue by ali6836** [rom1504/rbot#52]
Sometimes bot only shows Welcomes and Leaves in the Terminal and therefore doesnt detect my commands

**Comment by Ryah** [comment]
Does it show something like this?
`I logged in.
settings { chat: 'enabled',
  colorsEnabled: true,
  viewDistance: 'far',
  difficulty: 2,
  showCape: true }
hello, Wireless! welmove to the server.
Killed
`

That's the error I'm getting. It joins and then instantly leaves.

**Comment by ali6836** [comment]
@Ryah It's quite similar to that, I will add some code of my problem tomorrow probably.

**Comment by ali6836** [comment]
@Ryah This is what happens for me: 
I logged in.
settings { chat: 'enabled',
  colorsEnabled: true,
  viewDistance: 'far',
  difficulty: 2,
  showCape: true }
hello, xzoras! welmove to the server.
hello, NanomitesO_o! welmove to the server.
hello, Pillow_Cat! welmove to the server.
hello, liamiscool72! welmove to the server.
hello, walaksarsoor2020! welmove to the server.
hello, iAmWHALEY! welmove to the server.
hello, flower121! welmove to the server.
hello, Musicmanpiano18! welmove to the server.
hello, Matthias1266! welmove to the server.
hello, HuntingDarkos! welmove to the server.
hello, Flare_Charger! welmove to the server.
I have 20 health and 17 food
game { levelType: 'default',
  gameMode: 'survival',
  hardcore: false,
  dimension: 'overworld',
  difficulty: 'normal',
  maxPlayers: 60 }
hello, Want_Chocolates! welmove to the server.
bye HuntingDarkos

**Comment by rom1504** [comment]
fixed
