### ISSUE TITLE
help

### ISSUE THREAD

**Issue by huizichin** [rom1504/rbot#56]
So to start the bot i have to run this command
rbot <host> <port> <name> <password> [<master>]

What is host what is port, what is name and password what do i fill in?

Do i fill it like  
rbot host port name password master
or like the example you give?

The example you give is  
rbot <host> <port> <name> <password> [<master>]

**Comment by rom1504** [comment]
https://github.com/rom1504/rbot/blob/master/README.md#usage

**Comment by rom1504** [comment]
Host is the server , port is the port of the server
Username is the account username
Password is the account password

**Comment by rom1504** [comment]
Master is the username of the controlling user (optional)

**Comment by huizichin** [comment]
can i use it on cracked minecraft server?
if yes how?
