### ISSUE TITLE
Error when entering

### ISSUE THREAD

**Issue by mpamop** [rom1504/rbot#67]
When bot entering to server, script crashes.

> Chunk size is 21 but only 2 was read ; partial packet : {"name":"entity","params":{"entityId":0}}; buffer :2500000e9d010000000001000764656661756c7400
> Chunk size is 52 but only 5 was read ; partial packet : {"name":"transaction","params":{"windowId":2,"action":1,"accepted":true}}; buffer :110200010116000461726773106272696761646965723a737472696e6702146d696e6563726166743a61736b5f73657276657200
> C:\Users\mpamop\Desktop\mbot\node_modules\minecraft-protocol\src\transforms\framing.js:66
>           } else { throw e }
>                    ^
> 
> TypeError: Cannot read property 'id' of undefined
>     at confirmTransaction (C:\Users\mpamop\Desktop\mbot\node_modules\mineflayer\lib\plugins\inventory.js:452:21)
>     at Client.bot._client.on (C:\Users\mpamop\Desktop\mbot\node_modules\mineflayer\lib\plugins\inventory.js:564:5)
>     at Client.emit (events.js:189:13)
>     at FullPacketParser.deserializer.on (C:\Users\mpamop\Desktop\mbot\node_modules\minecraft-protocol\src\client.js:82:12)
>     at FullPacketParser.emit (events.js:189:13)
>     at addChunk (C:\Users\mpamop\Desktop\mbot\node_modules\readable-stream\lib\_stream_readable.js:297:12)
>     at readableAddChunk (C:\Users\mpamop\Desktop\mbot\node_modules\readable-stream\lib\_stream_readable.js:279:11)
>     at FullPacketParser.Readable.push (C:\Users\mpamop\Desktop\mbot\node_modules\readable-stream\lib\_stream_readable.js:240:10)
>     at FullPacketParser.Transform.push (C:\Users\mpamop\Desktop\mbot\node_modules\readable-stream\lib\_stream_transform.js:139:32)
>     at FullPacketParser._transform (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\serializer.js:81:10)

And

> { PartialReadError: Deserialization error for play.toClient.named_sound_effect.soundCategory : Read error for params.named_sound_effect.soundCategory : undefined
>     at new ExtendableError (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:62:11)
>     at new PartialReadError (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:68:5)
>     at ProtoDef.readVarInt (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\utils.js:69:45)
>     at ProtoDef.read (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\protodef.js:110:29)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:45:32)
>     at tryCatch (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:50:16)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:54:10)
>     at typeArgs.forEach (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:44:5)
>     at Array.forEach (<anonymous>)
>     at ProtoDef.readContainer (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:43:12)
>   name: 'PartialReadError',
>   message:
>    'Deserialization error for play.toClient.named_sound_effect.soundCategory : Read error for params.named_sound_effect.soundCategory : undefined',
>   partialReadError: true,
>   field: 'play.toClient.named_sound_effect.soundCategory' }
> { PartialReadError: Deserialization error for play.toClient.named_sound_effect.y : Read error for params.named_sound_effect.y : undefined
>     at new ExtendableError (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:62:11)
>     at new PartialReadError (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:68:5)
>     at ProtoDef.reader (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\numeric.js:61:48)
>     at ProtoDef.read (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\protodef.js:110:29)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:45:32)
>     at tryCatch (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:50:16)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:54:10)
>     at typeArgs.forEach (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:44:5)
>     at Array.forEach (<anonymous>)
>     at ProtoDef.readContainer (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:43:12)
>   name: 'PartialReadError',
>   message:
>    'Deserialization error for play.toClient.named_sound_effect.y : Read error for params.named_sound_effect.y : undefined',
>   partialReadError: true,
>   field: 'play.toClient.named_sound_effect.y' }
> { PartialReadError: Deserialization error for play.toClient.player_info.data.0.UUID : Read error for params.player_info.data.0.UUID : undefined
>     at new ExtendableError (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:62:11)
>     at new PartialReadError (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:68:5)
>     at ProtoDef.readUUID (C:\Users\mpamop\Desktop\mbot\node_modules\minecraft-protocol\src\datatypes\minecraft.js:18:44)
>     at ProtoDef.read (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\protodef.js:110:29)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:45:32)
>     at tryCatch (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:50:16)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:54:10)
>     at typeArgs.forEach (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:44:5)
>     at Array.forEach (<anonymous>)
>     at ProtoDef.readContainer (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:43:12)
>   name: 'PartialReadError',
>   message:
>    'Deserialization error for play.toClient.player_info.data.0.UUID : Read error for params.player_info.data.0.UUID : undefined',
>   partialReadError: true,
>   field: 'play.toClient.player_info.data.0.UUID' }
> { PartialReadError: Deserialization error for play.toClient.attach_entity.entityId : Read error for params.attach_entity.entityId : undefined
>     at new ExtendableError (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:62:11)
>     at new PartialReadError (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:68:5)
>     at ProtoDef.reader (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\numeric.js:61:48)
>     at ProtoDef.read (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\protodef.js:110:29)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:45:32)
>     at tryCatch (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:50:16)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:54:10)
>     at typeArgs.forEach (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:44:5)
>     at Array.forEach (<anonymous>)
>     at ProtoDef.readContainer (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:43:12)
>   name: 'PartialReadError',
>   message:
>    'Deserialization error for play.toClient.attach_entity.entityId : Read error for params.attach_entity.entityId : undefined',
>   partialReadError: true,
>   field: 'play.toClient.attach_entity.entityId' }
> { PartialReadError: Deserialization error for play.toClient.explosion.y : Read error for params.explosion.y : undefined
>     at new ExtendableError (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:62:11)
>     at new PartialReadError (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:68:5)
>     at ProtoDef.reader (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\numeric.js:61:48)
>     at ProtoDef.read (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\protodef.js:110:29)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:45:32)
>     at tryCatch (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:50:16)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:54:10)
>     at typeArgs.forEach (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:44:5)
>     at Array.forEach (<anonymous>)
>     at ProtoDef.readContainer (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:43:12)
>   name: 'PartialReadError',
>   message:
>    'Deserialization error for play.toClient.explosion.y : Read error for params.explosion.y : undefined',
>   partialReadError: true,
>   field: 'play.toClient.explosion.y' }
> { PartialReadError: Deserialization error for play.toClient.explosion.y : Read error for params.explosion.y : undefined
>     at new ExtendableError (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:62:11)
>     at new PartialReadError (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:68:5)
>     at ProtoDef.reader (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\numeric.js:61:48)
>     at ProtoDef.read (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\protodef.js:110:29)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:45:32)
>     at tryCatch (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:50:16)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:54:10)
>     at typeArgs.forEach (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:44:5)
>     at Array.forEach (<anonymous>)
>     at ProtoDef.readContainer (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:43:12)
>   name: 'PartialReadError',
>   message:
>    'Deserialization error for play.toClient.explosion.y : Read error for params.explosion.y : undefined',
>   partialReadError: true,
>   field: 'play.toClient.explosion.y' }
> { Error: Deserialization error for play.toClient : Read error for name : 84 is not in the mappings value
>     at ProtoDef.readMapper (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\utils.js:30:34)
>     at ProtoDef.read (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\protodef.js:110:29)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:45:32)
>     at tryCatch (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:50:16)
>     at tryDoc (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\utils.js:54:10)
>     at typeArgs.forEach (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:44:5)
>     at Array.forEach (<anonymous>)
>     at ProtoDef.readContainer (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\datatypes\structures.js:43:12)
>     at ProtoDef.read (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\protodef.js:36:25)
>     at ProtoDef.read (C:\Users\mpamop\Desktop\mbot\node_modules\protodef\src\protodef.js:110:29) field: 'play.toClient' }

What i'm doing wrong?

**Comment by rom1504** [comment]
What minecraft version ?

**Comment by mpamop** [comment]
I'm using 1.8.8 and 1.12.x, but server is 1.8 - 1.13

**Comment by rom1504** [comment]
Ok that's the problem, your server is not vanilla and is doing something
that doesn't seem supported by mineflayer.
Try on a vanilla server ?

**Comment by rom1504** [comment]
Try to specify the version though

**Comment by mpamop** [comment]
I'm tried on a local server, and it works!
Thanks for support.

(i'm not found file, answering for version)
